### PR TITLE
Add root options to manifest

### PR DESCRIPTION
**Pull request by TheHercules**

### CODE REVIEW

**Comment by TheHercules** [comment]
Still needed after this? https://github.com/AIMROM/android_build/compare/b7f339421e6e...7be4311b280f

**Comment by ShadowReaper1** [comment]
@TheHercules Bish look at the date i commented 😒.

**Comment by TheHercules** [comment]
@ShadowReaper1 Sorry. Checked my git after a long time 🙈

**Comment by manikchathli** [comment]
@TheHercules 😂

**Pull request closed without merging**
